"""update password length in authentity

Revision ID: 5e334478be5d
Revises: 9ac38e6008d4
Create Date: 2024-08-20 17:03:39.502577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e334478be5d'
down_revision: Union[str, None] = '9ac38e6008d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_entity', 'username',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('auth_entity', 'password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_entity', 'password',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('auth_entity', 'username',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
