"""alter subscribe column name

Revision ID: 5ef7c2399b55
Revises: 738224e87f84
Create Date: 2024-08-18 16:15:01.203798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ef7c2399b55'
down_revision: Union[str, None] = '738224e87f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('first_name', sa.String(length=200), nullable=False))
    op.add_column('subscribe', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.drop_column('subscribe', 'firstname')
    op.drop_column('subscribe', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('lastname', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('subscribe', sa.Column('firstname', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('subscribe', 'last_name')
    op.drop_column('subscribe', 'first_name')
    # ### end Alembic commands ###
