"""update AuthEntity

Revision ID: 5fcdb6a3a245
Revises: 5e334478be5d
Create Date: 2024-10-02 11:48:43.430768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fcdb6a3a245"
down_revision: Union[str, None] = "5e334478be5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_entity", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "auth_entity", sa.Column("last_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "auth_entity", sa.Column("company", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "auth_entity", sa.Column("phone", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "auth_entity",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "auth_entity",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.drop_index("username", table_name="auth_entity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("username", "auth_entity", ["username"], unique=True)
    op.drop_column("auth_entity", "is_active")
    op.drop_column("auth_entity", "is_admin")
    op.drop_column("auth_entity", "phone")
    op.drop_column("auth_entity", "company")
    op.drop_column("auth_entity", "last_name")
    op.drop_column("auth_entity", "first_name")
    # ### end Alembic commands ###
