"""create contact email relationship

Revision ID: 785cc67b474b
Revises: c4fd3aec553b
Create Date: 2024-08-18 11:16:01.469858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785cc67b474b'
down_revision: Union[str, None] = 'c4fd3aec553b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.drop_column('email', 'contact_id')
    # ### end Alembic commands ###
