"""update authentity

Revision ID: 9ac38e6008d4
Revises: a8eebc8e8331
Create Date: 2024-08-20 14:53:06.898624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac38e6008d4'
down_revision: Union[str, None] = 'a8eebc8e8331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_entity', sa.Column('email', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_entity', 'email')
    # ### end Alembic commands ###
