"""create facility

Revision ID: a1da72d0012c
Revises: 5fcdb6a3a245
Create Date: 2024-10-18 16:12:06.023491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1da72d0012c'
down_revision: Union[str, None] = '5fcdb6a3a245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility')
    # ### end Alembic commands ###
