"""create email

Revision ID: c4fd3aec553b
Revises: aeda8fc7b3fd
Create Date: 2024-08-17 18:22:15.540531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fd3aec553b'
down_revision: Union[str, None] = 'aeda8fc7b3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('sender', sa.String(length=200), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('cc', sa.String(length=500), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
